knowledge_creation:
  chunking:
    semantic_rules:
      - "Always keep section headers with their immediate content"
      - "Keep feature lists and technical specifications together with their parent section"
      - "Maintain the relationship between titles/subtitles and their descriptions"
      - "For lists of features or capabilities, keep the entire list in one chunk"
      - "Keep related concepts together, especially for lists and feature descriptions"
      - "Preserve technical terms and their definitions together"
      - "Keep API endpoints with their parameters and descriptions"
    overlap_size: 150
    min_chunk_size: 200
    max_chunk_size: 1500
    
  entity_extraction:
    model: "o3-mini-2025-01-31"
    confidence_threshold: 0.5
    system_prompt: |
      You are a knowledge extraction system. Extract entities and relationships from text.
      ONLY output a valid JSON object with this structure:
      {
        "entities": [
          {
            "name": "<entity name>",
            "type": "<PERSON|ORGANIZATION|LOCATION|TECHNOLOGY|CONCEPT|EVENT|PRODUCT>",
            "metadata": {"confidence": 0.7}
          }
        ],
        "relationships": [
          {
            "source": "<source entity name>",
            "target": "<target entity name>",
            "type": "<relationship type>",
            "metadata": {"confidence": 0.7}
          }
        ]
      }
      DO NOT include any text outside the JSON.
    extraction_prompt_template: |
      Extract entities and relationships from this text:
      
      {text}
      
retrieval:
  search:
    top_k: 10
    vector_weight: 0.75
    text_weight: 0.25
    min_similarity_score: 0.4
    context_window_size: 2
    
  response_generation:
    temperature: 0.3
    max_tokens: 1500
    citation_style: "inline"
    include_confidence: true
    prompt_template: |
      Answer the following technical question based on the provided context.
      Focus on accuracy and technical details.
      Include specific features, capabilities, and technical specifications when relevant.
      
      Question: {query}
      
      Context:
      {context}
      
      Please provide a comprehensive answer that:
      1. Uses information from all relevant chunks
      2. Maintains proper technical context
      3. Cites specific features and capabilities
      4. Indicates confidence level for technical claims
      5. Preserves technical terminology exactly as specified
      6. Focuses on accuracy and technical details
      7. Don't offer any assumptions or interpretations
      8. Don't repeat any of the input text
      9. Don't make up a filename or assume a specific format
      
      Answer:
